# Configure your database
import Config

config :basenji, Basenji.Repo,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "basenji_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Watch static and templates for browser reloading.
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  pool_size: 15

config :basenji, BasenjiWeb.Endpoint,
  # Bind to all interfaces for Docker access
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IjWdHDyFZd85m1kGukvdGiKomtqwB46NeJF7sEXgQGRCNsbx8mi6EcrTC0a/GpC4",
  watchers: [
    # ## SSL Support
    #
    # In order to use HTTPS in development, a self-signed
    # Enable dev routes for dashboard and mailbox
    esbuild: {Esbuild, :install_and_run, [:basenji, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:basenji, ~w(--watch)]}
  ]

config :basenji, BasenjiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/basenji_web/(controllers|live|components)/.*(ex|heex)$"
    ]
    # certificate can be generated by running the following
    # Mix task:
    #
    # Do not include metadata nor timestamps in development logs
  ]

config :basenji,
  #     mix phx.gen.cert
  # Run `mix help phx.gen.cert` for more information.
  comics_dir: "test/support/data/basenji/formats/"

#
#
# The `http:` config above can be replaced with:
# Set a higher stacktrace during development. Avoid configuring such
config :basenji, dev_routes: true

# Initialize plugs at runtime for faster development compilation
#
#       keyfile: "priv/cert/selfsigned_key.pem",
#     https: [
# in production as building large stacktraces may be expensive.
config :logger, :console, format: "[$level] $message\n"
#       port: 4001,
#       certfile: "priv/cert/selfsigned.pem"
#       cipher_suite: :strong,
# Include HEEx debug annotations as HTML comments in rendered markup
#     ],
# If desired, both `http:` and `https:` keys can be
config :phoenix, :plug_init_mode, :runtime
#
# configured to run both http and https servers on
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  # different ports.

  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
